### ISSUE TITLE
Some examples?

### ISSUE THREAD

**Issue by Sigfried** [toomuchdesign/re-reselect#10]
Hi,

This seems great, but for the slow among us, some examples in the documentation would be nice:
- The ways of calling a cachedSelector without getMatchingSelector if that's possible
- How to use the cachedSelector in the FAQ example
- How to use cachedSelectors as arguments to other selectors
- If you connect a cachedSelector to state in one place (like mapStateToProps) and then want to specify the cacheKey later (in a component or something), how do you do that?

Thanks so much!

**Comment by toomuchdesign** [comment]
Hi @Sigfried!
Probably the most of your doubts (1,2,3) come from the docs not being clear enough at explaining that **a cachedSelector behaves just like a normal selector** (!).

cachedSelectors can be directly called with the arguments you'd use for a normal selector. `getMatchingSelector` is just an additional method for debugging.

You can initialize both `reselect` or `re-reselect` selectors and use them in your application in the same way. In other words `re-reselect` should be transparent to the application.

@Sigfried, where could we improve the docs and get rid of this misunderstanding?

Concerning point 4, I have to think about it. I'll get back to you soon.
Looking forward for your feedback. Thank you!

**Comment by Sigfried** [comment]
Hi @toomuchdesign 

I think the documentation may already say that, but it still doesn't quite make it into my skull. One possibility is to show how you would do https://github.com/reactjs/reselect#containersvisibletodolistjs-3 with re-reselect.

Also, I think what confuses me most is, I look at the first example in the documentation and I understand `const fooSelector = cachedSelector(state, 'foo');` will give me a selector keyed on 'foo'. But if all my selectors are in some other file and all depending on each other, then I won't know that my key is 'foo' when I define the selector that's supposed to be cached. So, even if I do have my state and my key available at the same time, my regular selectors just need to passed a state argument, but my cached selectors need to be passed state and key arguments. So, if a regular selector refers to a cached selector, where does it get the key that the cached selector needs?

I'm sure I've hopelessly misunderstood how all this is supposed to work, but maybe that description gives you some sense of what the documentation might need to set people like me straight.

Thanks!

**Comment by toomuchdesign** [comment]
You actually caught a huge typo in the docs, @Sigfried!

`fooSelector` and `barSelector` from the first example, are absolutely NOT selectors, but just the results of the queried `cachedSelector `.

The example initializes a cached `re-reselect` selector which is then called with the state and 'foo/bar' as arguments. `re-reselect` selectors always return the result of the computed data.

Moreover I wasn't aware [reselect docs](https://github.com/reactjs/reselect#containersvisibletodolistjs-3) explicitly mentioning re-reselect among its "sharing selectors" examples. What a honour!

I'll keep this issue open until the docs being update with:
- First example fixed with proper names for `fooSelector` and `barSelector` 
- Re-reselect implementation of [reselect shared selectors example](https://github.com/reactjs/reselect#containersvisibletodolistjs-3)

@Sigfried please ping me if you find further updates to be done in the docs. Thank you! Cheers!!

**Comment by Sigfried** [comment]
Great! I'm thrilled my confusion has been good for something :)

**Comment by toomuchdesign** [comment]
Back to your fourth point:

> If you connect a cachedSelector to state in one place (like mapStateToProps) and then want to specify the cacheKey later (in a component or something), how do you do that?

You can't directly specify the cachedSelector cacheKey. Instead, when you initialize your cachedSelector, you have to provide a resolver function, which is the function that - given selector's arguments - compute the cacheKey.

Later, when you connect a `cachedSelector` to a `mapStateToProps`, you'll probably feed the selector with the state and some other arguments.

Once the `cachedSelector` is called, it computes the cacheKey with the provided arguments, and decides whether delegating the computation to a cached selector or a new one.

Any better? :)

Cheers!

**Comment by toomuchdesign** [comment]
Readme revamped! Still open to any suggestion.

**Comment by Slapbox** [comment]
I'd love some more examples, especially regarding this example https://github.com/toomuchdesign/re-reselect/blob/master/examples/1-join-selectors.md

I'm new to both this library and Reselect itself, but it seems like Reselect doesn't allow arguments to be passed in this way, and this is the only example to study as far as I can find. I'm a bit confused about how data is passed in/referenced by name.
