### ISSUE TITLE
[Feature request] Typescript typings

### ISSUE THREAD

**Issue by karptonite** [toomuchdesign/re-reselect#11]
This is a nice little library! It would be awesome if someone who knows enough typescript could add a typings file for typescript users. I have some interest in trying it out in my Angular/ngrx project, but that would work more smoothly if typings were available.

**Comment by toomuchdesign** [comment]
Hi @karptonite, I don't use Typescript, but I'm open to add typings to support TS users.

Would you be able to point me out any resource about TS typings? And, of course, would you like to give it a try?

Cheers!

**Comment by karptonite** [comment]
@toomuchdesign Sorry for the slow reply--I just noticed your comment.

While I use typescript, I am far from an expert--I've hardly even ever looked in a typescript definitions file, let alone used one. Here are some good resources about them:
http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
http://definitelytyped.org/guides.html

Here is a good and relevant example of a typescript typings file: https://github.com/reactjs/reselect/blob/master/src/index.d.ts.

But it may be that I posted this request in the wrong place; it looks like the Typescript community handles this sort of thing in a central location: https://github.com/DefinitelyTyped/DefinitelyTyped. I'm reluctant to post a request there, since I've since decided that re-reselect may not be the best fit to be used with ngrx/store, and I don't want to post a request for something I might not even end up using.

**Comment by toomuchdesign** [comment]
Thanks @karptonite, I'll keep the issue open. Typings would be a nice thing to add.

**Comment by sushain97** [comment]
Here's a start https://gist.github.com/sushain97/55af69be5694f40f9a24a48bbce07ce3 that might be helpful.

**Comment by toomuchdesign** [comment]
Thank you @sushain97! I'll study your gists and sort out how to complete your code.

**Comment by toomuchdesign** [comment]
Closed by [**v0.6.0**](https://github.com/toomuchdesign/re-reselect/releases/tag/v0.6.0).
