### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by adamgajzlerowicz** [toomuchdesign/re-reselect#114]
I'd like to use object as a param of a selector

I found this page and looks like what I need [link](https://github.com/toomuchdesign/re-reselect/tree/master/src/cache#readme) But I can't seem to be able to get it to work.

```
const keySelector = (state, params) => JSON.stringify(params)

const selectData = createCachedSelector(
  selectState,
  (data, params) => params, // params is an object
  (data, params) => {
    const result = something // compute
    return result
  },
)({
  keySelector,
  cacheObject: new LruObjectCache({ cacheSize: 5 }),
})
```

I also tried 

```
const selectData = createCachedSelector(
  selectState,
  (datae, params) => params,
  (data, params) => {
    const result = something // compute
    return result
  },
)((state, params) => JSON.stringify(params))
```

Both of the above are recomputing each time. What am I missing?

Can you please provide an example in the documentation? 

Many thanks!

**Comment by toomuchdesign** [comment]
Hi @adamgajzlerowicz,
there is a lot of missing information to tell what's going wrong. I can see a couple of things.

1) `createCachedSelector` accept the same arguments as reselect's `createSelector`. In your example I'd expect the last parameter function...
```
 (data, params) => {
    const result = something // compute
    return result
  }
```
...to be a `resultFunc` accepting the results of the previous `inputSelectors` as parameters.

 2) I'm pretty sure you don't want to use stringified object as `keySelector`.

**Comment by adamgajzlerowicz** [comment]
Can you please let me know what information you are missing? I will be happy to provide it!

ad 1. Re-reselect and reselect should the same interface, so I believe my code is correct

ad 2. What should be returned from the key extractor if not a string? Please correct me if I am wrong, but I think that the method you use to generate the string should not matter.

**Comment by xsburg** [comment]
Hi @adamgajzlerowicz,
A few problems might result in such a behavior and the example is rather abstract to tell what exactly goes wrong.
First of all, I would suggest you re-check that the parameters `data` and `params` in your final function only change when you expect them to change. For example:
```
mySelector(state, { param1: ‚foo', param2: ‚bar‘ })
mySelector(state, { param1: ‚foo', param2: ‚bar‘ }) // Wrong: params object is recreated each time, will cause recalculation
```
But the problem might be deeper, for example the `selectState` function might always produce a new object, or it might produce a new object when you do not expect that.

Regarding using a stringified object as a `keySelector`. It might result in stringifying rather large objects, as well as unexpected behavior: `JSON.stringify({ a: 1, b: 2 } ) !== JSON.stringify({ b: 2, a: 1 } )`. I would suggest either do it manually or generate a more precise code for serialization (one approach is provided in [this example](https://github.com/toomuchdesign/re-reselect/blob/master/examples/4-programmatic-keyselector-composition.md)).

**Comment by adamgajzlerowicz** [comment]
They params data passed as config is an object from react hook. It does change but then it changes back. Which is is what I want it to do as I'd like it to not recompute but use cached value.

I have it working now, by passing stringified config, and parsing it in selector, but this couples component logic with re-reselect :( 
I guess I could pass it twice - once as a config and second time as a custom cache key.

Seems that keySelectorCombiner expect all values to be strings (if I understand it correctly).

I am passing as params data from a form:
```
export type SelectType = {
  value: string
  label: string
}
export type InitialValuesType = {
  dataSources: SelectType[]
  campaigns: SelectType[]
  dataSourceVisible: boolean
  campaignVisible: boolean
}
```

So `keySelectorCombiner` won't work for me.

I wish I could just do this:

```
const selectData = createCachedSelector(
  selectState,
  (datae, params) => params,
  (data, params) => {
    const result = something // compute
    return result
  },
)((state, params) => JSON.stringify(params))
```

This way it would use the same interface as params passed in a form of a string.

It would be awesome if you can provide a working example with object passed as param (or as one of selectors)

I need to think a bit more abou this. If you have any hints, I'd appreciate it.

In a mean time I am closing the ticket. Thank you for your time!

**Comment by xsburg** [comment]
If the goal is to pass all extra parameters inside one `params` object, the parameters that you really need can always be selected:
```javascript
const selectData = createCachedSelector(
  selectState,
  (data, params) => params.param1,
  (data, params) => params.param2,
  (data, param1, param2) => {
    const result = something // compute
    return result
  },
)((state, params) => `${params.param1}:${params.param2}`)
```
This way you can preserve the original interface. Of course, assuming that the `data`, `param1` and `param2` objects do not change similarly to the params object. If they do, that would be another story of creating a separate selector for them (probably, depending on the use case).
