### ISSUE TITLE
Cache size

### ISSUE THREAD

**Issue by maartenschumacher** [toomuchdesign/re-reselect#13]
Should we be able to specify a cache size? There's nothing stopping the cache from growing infinitely, short of calling `clearCache()`, but a cache size might be a nicer way to guard against it.

**Comment by toomuchdesign** [comment]
Hi @maartenschumacher,
it's a feature a was considering, but I wouldn't like to bloat the code with too much _"cache-management"_ stuff.

Personally I've never push an application to the limit where re-reselect cache size is able to become a problem. Probably those edge cases, could be handled with a couple of line of code and a call to `clearCache()` or `removeMatchingSelector()`.

As a matter of interest, [Lodash's `memoize`](https://lodash.com/docs/4.17.4#memoize) does not provide cache management API's, neither.

That said, I'm open to different points of view!

**Comment by bratushka** [comment]
Maybe #23 can help

**Comment by toomuchdesign** [comment]
Added in [v1.0.0](https://github.com/toomuchdesign/re-reselect/releases/tag/v1.0.0). Thank you all for your contribution! 👏
