### ISSUE TITLE
getMatchingSelector can return OutputParametricSelector

### ISSUE THREAD

**Issue by Dante-101** [toomuchdesign/re-reselect#15]
In the typescript definitions, line 29, `getMatchingSelector: (state: S, ...args: any[])` returns `ParametricSelector<S, P, R>;`

My tests (which are passing successfully) are expecting an `OutputParametricSelector` with `recomputations` and `resetcomputations` functions on them. It will be great to change the definition to 
```
getMatchingSelector: (state: S, ...args: any[]) => OutputParametricSelector<S, P, R, any>;
```
Using `any` is not the best solution but it definitely is better than using `ParametricSelector`

**Comment by toomuchdesign** [comment]
Fixed by [**v0.6.1**](https://github.com/toomuchdesign/re-reselect/releases/tag/v0.6.1).
