### ISSUE TITLE
Use global.Reselect instead of global.reselect

### ISSUE THREAD

**Issue by cnlon** [toomuchdesign/re-reselect#17]
Error:
```
Uncaught TypeError: Cannot read property 'createSelector' of undefined
at dist/index.js:26
```
'reselect' is added as `window.Reselect`. But 're-reselect' gets 'reselect' by 'window.reselect'

**Comment by toomuchdesign** [comment]
Thank you @cnlon. Should be fixed by [**v0.6.2**](https://github.com/toomuchdesign/re-reselect/releases/tag/v0.6.2).
Cheers!
