### ISSUE TITLE
[suggestion] More explicit example of multiple inputs to set the cache key

### ISSUE THREAD

**Issue by Tyrame** [toomuchdesign/re-reselect#22]
I lost some time figuring out that the `resolverFunction` can return a string and allow this:

```typescript
createCachedSelector(
  ...
)((state, props) => `${props.arg1}:${props.arg2}`)
```

I even wrote a patch to allow the `resolverFunction` to return an array before realizing this, and feeling dumb...

It would be nice to have an example illustrating this case in the documentation :)

**Comment by toomuchdesign** [comment]
Hi @Tyrame, thanks for your feedbacks!
Do you have any suggestion about where the example should be added? Where you would have liked to read about it?

PR are welcome if you are like it.
Cheers!

**Comment by Tyrame** [comment]
I think the FAQ would be a nice place :)

**Comment by toomuchdesign** [comment]
Added in [bd2e125](https://github.com/toomuchdesign/re-reselect/commit/8e2064721083cd799e2bcedc576be512a52b5be0).
