### ISSUE TITLE
In TS, import and require syntax give difference behaviors

### ISSUE THREAD

**Issue by XilinJia** [toomuchdesign/re-reselect#223]
### Do you want to request a _feature_ or report a _bug_?
Bug
...

### What is the current behaviour?
In TS, import and require syntax give difference behaviors
...

### What is the expected behaviour?
both syntax should function the same or at least it should be better with import syntax
...

### Steps to Reproduce the Problem

1. define this:
```
const selectObjectByCommands = createCachedSelector(
	(state: any) => state.array,
	(array: any[]) => array,
)({
	keySelector: (_state: any, commandNames: string[]) => {
		return commandNames.join('_') : '';
	},
	selectorCreator: createShallowObjectEqualSelector,
});

let commandNames: string[] = ['text1', 'text2', 'text3'];
```
2. const { createCachedSelector } = require('re-reselect');
selectObjectByCommands({ array: output }, commandNames);

Things work.

3. import { createCachedSelector } from 're-reselect';
selectObjectByCommands({ array: output }, commandNames);

The function call becomes not valid and got complaint :
Expected 1 arguments, but got 2.
If called with:
selectObjectByCommands({ array: output });
Program crashes.

### Specifications

- Version: 4.0.1
- Platform: Linux
- Subsystem: Manjaro

**Comment by toomuchdesign** [comment]
Hi @XilinJia, thank for opening this issue.
In order to investigate this I'd need a reproduction repro. Would you be able to put together one?

Thank you
