### ISSUE TITLE
Wrapping existing reselect selectors?

### ISSUE THREAD

**Issue by jrnail23** [toomuchdesign/re-reselect#26]
In the docs, there's a section about [wrapping my existing selector with re-reselect](https://github.com/toomuchdesign/re-reselect#how-do-i-wrap-my-existing-selector-with-re-reselect), but I'd argue that instead of showing how to wrap an existing selector, it's merely showing how to _convert_ a `reselect` selector to a `re-reselect` selector.

But now I wanna know, is it possible to compose a `reselect` selector into `createCachedSelector`?

**Comment by toomuchdesign** [comment]
Hi @jrnail23,
if you mean using a `reselect` or a `re-reselect` selector as an `inputSelector` the answer is yes!

`re-reselect` selectors expose the same API as their `reselect` cousin's.
