### ISSUE TITLE
What can cause cachedSelector to recompute despite identical keySelector?

### ISSUE THREAD

**Issue by Nantris** [toomuchdesign/re-reselect#285]
### Do you want to request a _feature_ or report a _bug_?

Possible bug?

### What is the current behaviour?

Returning identical `keySelector` still recomputes constantly

### What is the expected behaviour?

Identical `keySelector` output causes recompute to be skipped.

### Steps to Reproduce the Problem

Unknown exactly, but something like this is what we use:
```js
  keySelector: state => {
    const {
      a = false,
      b = '',
      c = false,
      d = true,
      e = true,
      f = false,
      g,
    } = getOpts(state);

    return `${a}::${b}::${c}::${d}::${e}::${f}::${g}`;
  },

  cacheObject: new FifoObjectCache({ cacheSize: 10 }),
});
```

### Specifications

- Version: 4.0.1
- Platform: Linux
- Subsystem: ?

**Comment by toomuchdesign** [comment]
Hi @Nantris,
in order to provide support a [minimal repro is needed](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).
Chances are that something in user land is the cause of the issue you describe.

**Comment by Nantris** [comment]
@toomuchdesign thanks for your reply.

I'll see what I can put together - but I wonder if you have any general/generic advice regarding userland? I can't imagine what else could be at cause here, except having the wrong versions of `reselect` or `redux` for the version of `re-reselect` that we're using (but I confirmed that not to be the case.)

**Comment by toomuchdesign** [comment]
Please not that the expectation provided above is uncorrect:
> Identical keySelector output causes recompute to be skipped.

Identical `keySelector` causes the same `reselect` selector to be called.

Given a `keySelector`, the expected `reselect` selector will be called with provided `inputSelectors`.
