### ISSUE TITLE
Invalidate reselect cache only if resolverFunction is changed

### ISSUE THREAD

**Issue by vteremasov** [toomuchdesign/re-reselect#30]
In the docs [example](https://github.com/toomuchdesign/re-reselect#re-reselect-solution) is mentioned a code passing the state object in the first argument:
```
const getPieceOfData = createCachedSelector(
  state => state,
  (state, itemId) => itemId,
  (state, itemId, dataType) => dataType,
  (state, itemId, dataType, otherArg) => otherArg,
  (state, itemId, dataType, otherArg) => expensiveComputation(state, itemId, dataType, otherArg),
)(
  (state, itemId, dataType) => dataType,    // Memoize by dataType
);
```
Unfortunatly I couldn't reproduce this behavior and created a little test example.
It assumes we are using immutable js

```
const mySelector = createCachedSelector(
  state => state, 
  state => state.foo,
  state => state.bar, 
  (state, foo, bar) => {
    console.log('called');

    return foo + bar;
})(state => 'justString');

// Selector is called when the state is changed only 
// But if the state is changed it means it's a new object.
const res = mySelector({foo: 'foo', bar: 'bar'})
```
The selector function is not cached here and console.log always logs logged. Do I do anything wrong? or maybe it is impossible without custom cacheCreator?

**Comment by toomuchdesign** [comment]
Hi @vteremasov,
how are you calling your selector?

If called like this:
```
mySelector({foo: 'foo', bar: 'bar'});
mySelector({foo: 'foo', bar: 'bar'});
```
a new different state object is passed on each call.

`re-reselect` will use the same selector since `resolverFunction` result is locked to `'justString'`, but when the cached `reselect` selector is fired it will invalidate its cache since the first `inputSelector` (`state => state`) returns a different object object.

**Comment by vteremasov** [comment]
Oh, thank you, now I've got this. Is there any option to invalidate cache only if `resolverFunction` is changed? Even if new different objects are passed?

**Comment by toomuchdesign** [comment]
In this case you don't need `reselect` nor `re-reselect`. Just wrap your function with a memoization utility like Lodash's [memoize](https://lodash.com/docs/4.17.4#memoize).

**Comment by vteremasov** [comment]
Ok, thank you for help.
