### ISSUE TITLE
Any way to pass a custom equalityCheck?

### ISSUE THREAD

**Issue by zsaraf** [toomuchdesign/re-reselect#31]
First off, I love this library! 

I have a case where I need to pass a custom `equalityCheck` (performing a shallow check on an array vs the default reference check). The problem that I'm facing is that when composing my re-reselect with a reselect selector that performs the custom `equalityCheck`, I lose all of the performance benefits of re-reselect in the first place (as the reselect selector has a cache size of 1). Example:

```js
// Custom equality check function
const shallowArrayEqualityCheck = (currentVal, previousVal) => {
    if (currentVal.length !== previousVal.length) {
        return false
    }

    const length = currentVal.length
    for (let i = 0; i < length; i++) {
        if (currentVal[i] !== previousVal[i]) {
            return false
        }
    }

    return true
}

// Selector creator that uses my custom equalityCheck function
const createShallowEqualSelector = createSelectorCreator(
    defaultMemoize,
    shallowArrayEqualityCheck,
)

// Using the selector creator to fetch messages and memoize correctly (using shallow check)
const messagesSelector = createShallowEqualSelector(
    (state, chatroomId) => state.chatrooms[chatroomId].messages.map(messageId => getMessage(state, messageId)),
    messages => messages,
)

// Use cached selector to cache based on chatroom
const messagesCachedSelector = createCachedSelector(
    messagesSelector,
    messages => messages,
)(
    (state, chatroomId) => chatroomId,
)
```

Ultimately, I wish that I could pass in an equalityCheck to the cached selector, which would remove this issue!

Any thoughts/tips/ideas would be much appreciated!

**Comment by toomuchdesign** [comment]
Hi @zsaraf,
what you are probably looking for is [`selectorCreator` option](https://github.com/toomuchdesign/re-reselect#optionsselectorcreator). It accepts any **`reselect` custom selector creator** to be instantiated on the fly.

Back to your example it should be declared like this:

```js
import createCachedSelector from 're-reselect'; 

// ...

const messagesSelector = createCachedSelector(
    (state, chatroomId) => state.chatrooms[chatroomId].messages.map(messageId => getMessage(state, messageId)),
    messages => messages,
)(
    (state, chatroomId) => chatroomId,
    {
        selectorCreator: createShallowEqualSelector,
    }
);
```
You don't need to wrap your custom shallow selector creator into a `re-reselect` selector, but just let `re-reselect` use it.

**Comment by zsaraf** [comment]
Awesome, makes a lot of sense. Thanks!
