### ISSUE TITLE
Large cacheKey's not setting?

### ISSUE THREAD

**Issue by kevzettler** [toomuchdesign/re-reselect#36]
I noticed a huge performance hit in my project and tracked it down to a `createCachedSelector` that was constantly re-evaluating.

This `createCachedSelector` is unique to my other well behaving selectors in that it uses a generated `cacheKey` from another selector.

``` javascript
((state, props) => {
    const token = selectEntityItemAssetNamesToken(state, props);
    return token;
  });
```

The token that returns is a base64 hash string. here is an example:

```
"bWVjaHNuaXBlci1oYW5kcy1IZWFkLW1lY2hzbmlwZXItaGFuZHMtQ2hlc3QtbWVjaHNuaXBlci1oYW5kcy1Db3JlLW1lY2hzbmlwZXItaGFuZHMtV2Fpc3QtbWVjaHNuaXBlci1oYW5kcy1TaG91bGRlckwtbWVjaHNuaXBlci1oYW5kcy1CaWNlcEwtbWVjaHNuaXBlci1oYW5kcy1Bcm1MLW1lY2hzbmlwZXItaGFuZHMtSGFuZEwtbWVjaHNuaXBlci1oYW5kcy1TaG91bGRlclItbWVjaHNuaXBlci1oYW5kcy1CaWNlcFItbWVjaHNuaXBlci1oYW5kcy1Bcm1SLW1lY2hzbmlwZXItaGFuZHMtSGFuZFItbWVjaHNuaXBlci1oYW5kcy1UaGlnaEwtbWVjaHNuaXBlci1oYW5kcy1TaGluTC1tZWNoc25pcGVyLWhhbmRzLUZvb3RMLW1lY2hzbmlwZXItaGFuZHMtVGhpZ2hSLW1lY2hzbmlwZXItaGFuZHMtU2hpblItbWVjaHNuaXBlci1oYW5kcy1Gb290Ui1tZWNoc25pcGVyLWhhbmRzLUJhY2tQYWNr"
```

I've confirmed that these tokens are constants and not mutating.

If I change this selector to return a smaller key it caches correctly and does not re evaluate.
``` javascript
((state, props) => {
    return props.entityId;
  });
```
further more I can reproduce the issue with a static token like:
```javascript
((state, props) => {
    const token = "bWVjaHNuaXBlci1oYW5kcy1IZWFkLW1lY2hzbmlwZXItaGFuZHMtQ2hlc3QtbWVjaHNuaXBlci1oYW5kcy1Db3JlLW1lY2hzbmlwZXItaGFuZHMtV2Fpc3QtbWVjaHNuaXBlci1oYW5kcy1TaG91bGRlckwtbWVjaHNuaXBlci1oYW5kcy1CaWNlcEwtbWVjaHNuaXBlci1oYW5kcy1Bcm1MLW1lY2hzbmlwZXItaGFuZHMtSGFuZEwtbWVjaHNuaXBlci1oYW5kcy1TaG91bGRlclItbWVjaHNuaXBlci1oYW5kcy1CaWNlcFItbWVjaHNuaXBlci1oYW5kcy1Bcm1SLW1lY2hzbmlwZXItaGFuZHMtSGFuZFItbWVjaHNuaXBlci1oYW5kcy1UaGlnaEwtbWVjaHNuaXBlci1oYW5kcy1TaGluTC1tZWNoc25pcGVyLWhhbmRzLUZvb3RMLW1lY2hzbmlwZXItaGFuZHMtVGhpZ2hSLW1lY2hzbmlwZXItaGFuZHMtU2hpblItbWVjaHNuaXBlci1oYW5kcy1Gb290Ui1tZWNoc25pcGVyLWhhbmRzLUJhY2tQYWNr";
    return token;
  });
```

**Comment by toomuchdesign** [comment]
Hi @kevzettler,
Could you provide the code where you initialise the `re-reselect` selector with `createCachedSelector`? Are you using default `FlatCacheObject` cache?

Greetings!

**Comment by kevzettler** [comment]
@toomuchdesign

> Are you using default FlatCacheObject cache?

Yes.

I have since discovered that it is not specifically an issue with the length of the key, as I can reproduce with an addition of `token.substr(0,4)`. 

Does the `resolverFunction` expect a referential equal return value?

My `cteateCachedSelector` function is rather large and has external dependencies. I've included it below:

```javascript
export const selectPaletteForJoinedAssets = createCachedSelector(
  [selectEntityItemAssetNames, getAssets],
  function paletteForJoinedAssets(playerAssetNames, assets){
    console.log('regenerating palette for assets');
    return playerAssetNames.reduce((acc, assetName) => {
      var asset = assets[assetName];

      if(!acc.palette.length){
        acc.palette = asset.uniforms.palette;
        acc.paletteIdx = asset.attributes.paletteIdx
        return acc;
      }

      acc.paletteIdx = acc.paletteIdx.concat(asset.attributes.paletteIdx.map((localIdx) => {
        var localColor = asset.uniforms.palette[localIdx];
        var globalIdx = deepIndexOf(acc.palette, localColor);

        //If the local color is not in the global palette
        // add the local color to the global palatte and use the new index
        if(globalIdx === -1){
          acc.palette.push(localColor);
          return acc.palette.length-1;
        }

        //If the local color is in the global palette
        //but the local index dosen't match the global Index
        //use the global index instead
        if(globalIdx !== -1 && globalIdx !== localIdx){
          return globalIdx;
        }

        //Otherwise continue to use the local index
        return localIdx;
      }));

      return acc;
    }, {
      palette: [],
      paletteIdx: [],
    });
  })((state, props) => {
    const token = selectEntityItemAssetNames(state, props).join('|')
    return token
  });
```

**Comment by toomuchdesign** [comment]
> Does the resolverFunction expect a referential equal return value?

No, since it currently accepts only `strings` or `numbers`, JS compares them by value even with a `===`. 😃 

If `selectEntityItemAssetNames` returns a stable value in time given the same arguments, the problem might be somewhere else.

`re-reselect` stores a collection of normal `reselect` selectors in its cache. `resolverFunction` aim is to tell `re-reselect` if the **incoming request** can be resolved **by querying one of the cached selectors** or its necessary to **instantiate a new one**.

I suppose that the current `resolverFunction` is addressing too many request over a single cached `reselect` selector, which might receive **different arguments on each request** and  **invalidate its cache on each request**.

Just guessing:
what if, given the same `selectEntityItemAssetNames` result, `getAssets` returned a new object?

**Comment by kevzettler** [comment]
I have confirmed that both `selectEntityItemAssetNames`, `getAssets` are returning the same values.

In my original post I stated that if I change the `resolverFunction` to:

```
((state, props) => {
    const token = props.entityId;
    return token;
  });
```

or 
```
((state, props) => {
    return props.entityId;
  });
```

Behaves as expected and caches correctly. Why would that be the case?

If I change the `resolverFunction` to:
```
((state, props) => {
    return 'staticTokenStringWhatever';
  });
```
It does not cache.

**Comment by toomuchdesign** [comment]
A `resolverFunction` like this will cache a new `reselect` selector for any new `entityId`:
```js
(state, props) => props.entityId
```

A `resolverFunction` returning a static string, will cache a single`reselect` selector for all calls, invalidating its cache on each different request.
```js
(state, props) => 'staticTokenStringWhatever';
```
I'm not aware of any bug related to using large string as object keys.

Is `selectEntityItemAssetNamesToken` returning a unique value for any different item?

If the problem persisted and you wanted further support, would you mind providing the code necessary to reproduce the bug?

Thank you, have a good one!
