### ISSUE TITLE
Provide an example showing composition from dissimilar selectors/different slices of state

### ISSUE THREAD

**Issue by ChrisLincoln** [toomuchdesign/re-reselect#39]
First off, this lib has breathed fresh air into my app.  I am functional programming nube, so I tend to stumble through over-simplified examples.  I have some simple, cached selectors wired up by following the examples in your docs.  They look like this:

```javascript
const getAllData = state => state.sliceX;
const getSliceXByID = createCachedSelector(
    getAllData,
    (state, sliceXid)=> sliceXid,
    (allData, sliceXid) => {
        ...get stuff from allData using slice X ID
    }
)(
    (state, sliceXid) => sliceXid
)
```

On one particular nasty view, I need to merge, transform, and aggregate two slices of state. Each slice has a selector with the calling convention above--that works well elsewhere in the app:  getSliceXByID( xID ) and getSliceYByID( yID).  I can't wrap my brain around the syntax of composing a new selector from these two. The existing example that shows the re-reselect version of the reselect visibility derive data from the same slice of state keyed by the same id.  I need something showing disparate state slices:

```javascript
const getExpensiveMorphation = createCachedSelector(
   getSliceXByID,
   getSliceYByID,
   {..I get lost in the weeds here}
)(
   (state, sliceXid, sliceYid) =>...computed compound key of X and Y id. (this part I understand).
)
```
I notice the array [] input in the example and suspect that I need to keep that in play.

**Comment by toomuchdesign** [comment]
Hi @ChrisLincoln,
following `reselect` naming, `getSliceXByID` and `getSliceYByID` are `inputSelectors` while `{..I get lost in the weeds here}` is the `resultFunc`.

In order to write the selector you should consider that:
- All `inputSelector` receive the original arguments of the final selector
- `resultFunc` receives `inputSelectors` results as arguments

If `getSliceXByID` and `getSliceYByID` **expect the same arguments** (`state` and `sliceId`), the final selector might look like:

```
const getExpensiveMorphation = createCachedSelector(
   getSliceXByID,
   getSliceYByID,
   (dataFromSliceX, dataFromSliceY) => // Your selector logic
)(
   (state, sliceId) => sliceId
)

// To be called like
getExpensiveMorphation(state, sliceId);
```

If `getSliceXByID` and `getSliceYByID` **expect different arguments**, you might consider **normalizing one of the 2** by wrapping it into a another function:

```
const getExpensiveMorphation = createCachedSelector(
   getSliceXByID,
   (state, sliceXid, sliceYid) => getSliceYByID(state, sliceYid), // Normalize selectors arguments 
   (dataFromSliceX, dataFromSliceY) => // Your selector logic
)(
   (state, sliceXid, sliceYid) => `${sliceXid}:${sliceYid}`
)

// To be called like
getExpensiveMorphation(state, sliceXid, sliceYid);
```

**Comment by ChrisLincoln** [comment]
@toomuchdesign Thank you.  That is immensely helpful.  The **same arguments** constraint is exactly what I was stumbling over.  Now I see. I carry too many bad habits from other languages, so none of my selectors accept "props".   That is like passing a void* to a structure in C out of laziness. Both of the differing IDs do happen to be in the same props object at the point I need to invoke this thing, so I am going to do as you suggest by actually putting a shim on each that accepts props and produces the proper id for the real selector.
