### ISSUE TITLE
Key unique per selector or app

### ISSUE THREAD

**Issue by tim-field** [toomuchdesign/re-reselect#4]
Do I need to ensure that the cache key is unique for a selector, or for the whole application ? 

Seems to be per selector, so I could create two keys that are the same for different selectors I think ...

**Comment by toomuchdesign** [comment]
Hi @tim-field! The **cache key** has to be **unique just for the single selector.**

Each re-reselect selector [keeps its own selectors cache object ](https://github.com/toomuchdesign/re-reselect/blob/v0.1.0/index.js#L4).
