### ISSUE TITLE
Can selector functions be used to populate variables in the cacheKey?

### ISSUE THREAD

**Issue by Slapbox** [toomuchdesign/re-reselect#45]
I'd like to set the cacheKey using not only the input args, but also using selector functions. I can't find any way to do that. Trying to use anything besides input args seems to result in `undefined`

Sorry this question isn't very well formed. I find this library amazing, but I have trouble conceptualizing about it after using it only twice several months ago.

**Comment by toomuchdesign** [comment]
Hi @Slapbox,
would you please write down a concrete example of how the current `resolverFunction` implementation represents a limit in you use case?

Cheers!

**Comment by Slapbox** [comment]
Thanks for your reply @toomuchdesign! I don't know for sure that it does and that it's not just a misunderstanding on my part.

Here's a pared down example of what I have now and comments showing the selector I'd like to use in my `resolverFunction`, `getOpts`


```javascript
const getOutput = createCachedSelector(
  getEmail,
  getOpts, // <<< **I'd like to use this selector**
  (state, input) => input,
  (email, opts, input) => {
    /*  Some heavy processing  */
  }
)((state, input) => {
  const {
    uuid, updatedAt, status
  } = input;
  return `${uuid}::${updatedAt}::${status}`; // <<< **In this cache key**
});
```

**Comment by Slapbox** [comment]
I suppose more accurately what I'm looking for is a way to invalidate the cache, specifically when an option that the `cachedSelector` depends on changes.

**Comment by Slapbox** [comment]
I suppose more succinctly what I'm looking for is a way to invalidate the cache, specifically when an option that the `cachedSelector` depends on changes.

**Comment by toomuchdesign** [comment]
`resolverFunction` is called with same same arguments provided to the selector, in your case `state` and `input`.

I still don't get your goal, but calling `getOpts` inside `resolverFunction` should be still technically feasible, since its available in the declaration's lexical scope:

```js
(state, input) => {
  const {
    uuid, updatedAt, status
  } = input;
  const opts = getOpts(state, input);

  return `${uuid}::${updatedAt}::${status}`;
```
That said, it would be better to avoid calling the same selector twice and find a neater way to generate a meaningful `cacheKey`. But there is no rule, since the `cacheKey` is very dependent on the logic of each application.

**Comment by Slapbox** [comment]
Perhaps I'm approaching this fundamentally wrongly. I'll try to see if I can explain my situation a bit better after re-examining. Thanks for your responses and, of course, for re-reselect!

**Comment by toomuchdesign** [comment]
Of course! Feel free to re-open this issue if anything is still unclear.
Cheers!
