### ISSUE TITLE
 include key resolvers

### ISSUE THREAD

**Issue by jaimealv994** [toomuchdesign/re-reselect#47]
Is there a way to include key resolvers, for example, the way I use re-reselect is like this:

```javascript
const filterByPrecedence = createCachedSelector(
    getProps("documentTypes", "precedenceTitle"),
    (documentTypes, precedenceTitle) =>{
        return documentTypes.filter(({ precedence }) => precedence && precedence.title === precedenceTitle)
    }
)(processCacheName("documentTypes", "precedenceTitle"));
```
in this case I take data from state and I also process the documentTypes array as string because if a new reference of the array goes to the store, the selector is recomputed.

I would like to know your opion about this.

**Comment by toomuchdesign** [comment]
Hi @jaimealv994,
I'm not sure I got your example.

If the **result function** expects 2 arguments (`documentTypes`, `precedenceTitle`), I would expect the selector creator to be called with 2 **inputSelectors**.

What `getProps` and `processCacheName` do?
Don't they return the same value on every call when called with the same 2 string arguments?

**Comment by jaimealv994** [comment]
This proposal is to save time writing **input selectors**  and **resolver functions**.

So for example my store has this form
```json
{
  "documentTypes": [],
  "precedenceTitle": "",
  ...
}
```

And my selector looks like this

``` javascript
const filterByPrecedence = createCachedSelector(
    getProps("documentTypes", "precedenceTitle"),
    (documentTypes, precedenceTitle) =>{
        return documentTypes.filter(({ precedence }) => precedence && precedence.title === precedenceTitle)
    }
)(processCacheName("documentTypes", "precedenceTitle"));
```

and these are the helper fuctions
``` javascript
export const getProp = propName => data => data[propName];

export const getProps = (...props) => {
  return props.map(prop => getProp(prop));
};

export const processCacheName = (...props) => data => {
  return props
    .map(key => {
      const prop = getProp(key)(data);
      return typeof prop === 'object' ? JSON.stringify(prop) : prop;
    })
    .join(':');
};
```

So I call the selector like this ```filterByPrecedence(store)```. This can be impreved so you can pick a nested object like this "my.nested.object", or even pick values from store or props like this "store.my.nested.object", "props.my.nested.object".

**Comment by toomuchdesign** [comment]
It's a prefect valid way of using both `reselect` or `re-reselect`.
I personally find it a little bit over-engineered, but it's totally a matter of taste and kind of project. 😃
