### ISSUE TITLE
Selector recomputes every time

### ISSUE THREAD

**Issue by tizzle** [toomuchdesign/re-reselect#51]
### Do you want to request a _feature_ or report a _bug_?

It's more of a question on usage and clarification what i'm doing wrong. Depending on what is really happening, it might be a bug, but more likely just some additions to README.

### What is the current behaviour?

When using re-reselect with redux the selectors always recompute. I'm able to make simplified examples work, but when integrated into a more complex scenario, caching breaks.

I made a demo here: https://codesandbox.io/s/pmmry9j70m
If you click the "Select this article" button on the same item multiple times, the selector is recalculated.

Some background:
The buttons dispatch a thunk action that sets the `selectedArticle` – an object of multiple ids – in the state. This object is then retrieved in the connected 'App.js' and fed as props into the getArticle selector.

My current hypothesis is that the selectors recompute due to the state change in `selectedArticle`.

### What is the expected behaviour?

If you click the "Select this article" button on the same item multiple times, the selector should be pulled from cache, as the return value of the key resolver function did not change.

### Steps to Reproduce the Problem

1. Go to https://codesandbox.io/s/pmmry9j70m
2. Click the "Select this article" button multiple times on the same button
3. See the recomputations count rise

(If the buttons don't work, you may have to reload the sandbox)

### Specifications

* Version: 2.1.0
* Platform: -
* Subsystem: -

**Comment by tizzle** [comment]
I did some further investigations and found something. 

In the linked demo, i saved the selected article as an object into redux state:
```
selectedArticle: {
    articleId: "B4AC304E-43EC-4B98-9FA9-4B764B409A02",
    variantId: "AB12DD4D-D1B0-42F9-AA9F-0418F7FA3092",
    vendorId: "E5071F85-E4F1-45C4-896B-EC6F4C212057"
}
```

This object i then formatted as a string to use as a cache key:
```
const cacheKey = `${props.articleId}:${props.variantId}:${props.vendorId}`;
```
  
When rewriting the thunk action to create the cacheKey and saving this to redux store, the computations work fine. See forked demo:
https://codesandbox.io/s/myv299kp0x

Can anyone explain to me why this happens?

**Comment by toomuchdesign** [comment]
Hi @tizzle.
From what I can see, the difference between the 2 demos lays in the objects passed to `handleSetSelectedArticle` by the "select this article" button:

```js
onClick={() => {
  handleSetSelectedArticle({
    articleId: article.articleId,
    variantId: article.variantId,
    vendorId: article.vendorId
  });
}}

onClick={() => {
  handleSetSelectedArticle(article);
}}
```
The first example creates a new object on each callback, invalidating the `reselect` selector cache.

In order to retain memoization, every single `inputSelectors` should referentially return the same entity (`prevValue === newValue`) between 2 consequent calls.

**Comment by tizzle** [comment]
Hey @toomuchdesign,

thanks for your prompt reply and your awesome library! 
Passing a reference like in your example solves the issue.

I still don't get the problem i produced completely so i would be really grateful if you could elaborate further. Maybe my understanding of the `reselect` cache is just incomplete.

My assumption was that `reselect` only caches a slice of the redux store and thus is not invalidated when i change something elsewhere.

So when looking at my selector:
```
export const getArticle = createCachedSelector(
    getAllArticlesById,
    getAllVendorsById,
    (state, props) => props,
    (articles, vendors, props) => extractData(articles, vendors, props)
)((state, props) => {
    const cacheKey = `${props.articleId}:${props.variantId}:${props.vendorId}`;
    console.log("key resolver", cacheKey);
    return cacheKey;
});
```

I now assume that line 4 `(state, props) => props,` is causing the cache invalidation, because here i introduce a new object into the selector every time the button is clicked. Is that correct?

Thanks so much for help and feel free to close this issue.

Best regards,
Till

**Comment by toomuchdesign** [comment]
`getArticle` selector is meant to be called with the following arguments:

```js
getArticle(state, state.articles.selectedArticle)
```
The first demo replaced `state.articles.selectedArticle` in the state with a copy of the same object on each single button click, causing `reselect` to recalculate the result.

**Comment by tizzle** [comment]
Alright, i think i got it now, thanks a lot!
