### ISSUE TITLE
Typescript: isValidCacheKey() expects 0 arguments

### ISSUE THREAD

**Issue by el-dav** [toomuchdesign/re-reselect#56]
### Do you want to request a _feature_ or report a _bug_?

bug

### What is the current behaviour?

TS typings for isValidCacheKey should take an argument

### What is the expected behaviour?

isValidCacheKey('string') should not give a type error

### Steps to Reproduce the Problem

```
import createCachedSelector from 're-reselect';

type State = {
    id: string,
    thing: string
}

const baseSelector = (state: State) => state;
const resolver = (state: State) => state.id

const cachedSelector = createCachedSelector(baseSelector, (state) => state.thing)(resolver);

cachedSelector({
    id: '1',
    thing: 'thing1'
})

const cache = cachedSelector.cache;

cache.isValidCacheKey('1') // Type Error: Expected 0 arguments but got 1;
```

### Specifications

* Version: 2.1.0

**Comment by toomuchdesign** [comment]
Hi @el-dav,
I just merged a fix. Thank's for pointing out!

Closed by #57.
