### ISSUE TITLE
Documentation lacks any reference to `createStructuredSelector`

### ISSUE THREAD

**Issue by RichardForrester** [toomuchdesign/re-reselect#75]
### Do you want to request a _feature_ or report a _bug_?

No.

### What is the current behavior?

Re-reselect's documentation does not reference reselect's [`createStructuredSelector`](https://github.com/reduxjs/reselect#createstructuredselectorinputselectors-selectorcreator--createselector) and therefore it is not clear whether there is an equivalent function in re-reselect, e.g., `createCachedStructuredSelector`, or if there is some other recommended way to convert existing reselect structuredSelectors to re-reselect selectors, or if it is merely a "convenience" feature of reselect not requiring the explicit support of re-reselect.

### What is the expected behavior?

Unknown. Documentation should show an example of how this libraries authors' intend structuredSelectors to be converted to re-reselect structuredSelectors.

### Steps to Reproduce the Problem

Read documentation.

### Specifications

- Version: latest
- Platform: n/a
- Subsystem: n/a

**Comment by toomuchdesign** [comment]
Hi @RichardForrester,
re-reselect doesn't provide any enhanced version on reselect's `createStructuredSelector`.

Since `re-reselect` selectors expose the same interface as an original `reselect` selector, `createStructuredSelector` can transparently work with `re-reselect` selectors:

```js
import { createStructuredSelector } from 'reselect'

const structuredSelector = createStructuredSelector({
  x: mySelectorA, // can be a re-reselect selector
  y: mySelectorB,
})
```

**Comment by RichardForrester** [comment]
Right, there's not enough computation going in `createStructuredSelector` to warrant a cache. Still, I was half way to:

```typescript
import { keys, values, zipObj } from 'ramda'
import createCachedSelector, { Selector } from 're-reselect'

interface ICachedSelectorMap {
  [key: string]: Selector<any, any>
}

export const createCachedStructuredSelector = (cachedSelectorMap: ICachedSelectorMap) =>
  createCachedSelector(values(cachedSelectorMap), (...sResults) =>
    zipObj(keys(cachedSelectorMap) as string[], sResults)
  )
```
... before I realized it wasn't worth it.

A line in the docs with your example may save the next guy a little time.

Thanks for the great package - really blew me away with the performance benefits between DOM mounts/unmounts.

**Comment by toomuchdesign** [comment]
A cached version of `createStructuredSelector` is technically possible by extending the API with a `keySelector` like `re-reselect` does with normal selectors.

Since `createStructuredSelector` is just syntactic sugar I've never found a valid reason for making `re-reselect` codebase bigger.

**Comment by RichardForrester** [comment]
Ya, it's not worth adding anything to the code base, but not having a reference in docs threw me for a loop - probably because I'm converting a bunch of `makeGet`ers and so the data is already being assimilated in slightly different order - came across a structuredSelector deep in a chain of single-input single-output selectors and my brain went into convulsions.

**Comment by RichardForrester** [comment]
I'm still refactoring a large app converting selectors to cached selectors and I'm not so sure about the question of whether the API should be extended to add `createCachedStructuredSelector`. A reference should definitely be added to the docs, but on the question of the API, I think you could go either way.

You've either got to take the position that `createStructuredSelector` does not warrant caching because all it does is combine already existing selectors into a master selector and the CPU resources used to do that are less valuable than the RAM used to store the cache. I don't really know the answer to the issue of which resource is more valuable, but if an uncached `createStructuredSelector` in a long chain of cached selectors will cause any significant disruption or if the CPU resources used to recreate the structured selector on re-mounts is greater than memory used to store a cache, then extending the API with `createCachedStructuredSelector` makes sense.

**Comment by toomuchdesign** [comment]
Hi @RichardForrester,
is there anything preventing from using the non-sugared syntax in this case (following [reselect example](https://github.com/reduxjs/reselect/tree/v4.0.0#createstructuredselectorinputselectors-selectorcreator--createselector))?

```js
import createCachedSelector from 're-reselect';

const structuredSelector = createCachedSelector(
   mySelectorA,
   mySelectorB,
   (a, b) => ({
     a,
     b
   })
)(state => state.b)
```

**Comment by RichardForrester** [comment]
I think the answer to that question in every case has to be "no"; there must always be a way to use the longer form. However, on the project I am currently working, these objects are extremely large with dynamically named keys and dynamically named selectors, so the inconvenience is great enough that I would chose to either create my own helper (as in comment 3 above) or to use the reselect version and forego caching on just the structuredSelector.

However, I am dealing with a related problem at the moment that is perplexing me; it is possible that once I solve it, the pieces may fall in place and in a different order alleviating the concern.

I am likely now outside the scope this issue tracker, but the question that has me down the rabbit hole on all of this is how to best go about "two-trip" selectors - meaning I have no way to know what the keys and selectors of a structuredSelector are going to be until I a travel to the State to retrieve them, at which point I can construct and return a structuredSelector - of course, that structuredSelector would need to be called with the State argument to return the data - hence the "second" trip. Essentially, these "two-trip" selectors are "makers" similar those described in the reselect documentation albeit with the significant distinction that the arguments to this particular type of "maker" are not known until some data is retrieved from the State.

Usually, when I am needing to go this deep into a problem, there is some conceptual defect in my thought process, so I searching for that now by running lots of unit tests on different ideas and checking recalculations and such. This all started by refactoring "makers" into cachedSelectors, so the solution may actually be something simple like passing those unknown keys as props so they are known before mapStateToProps is evaluated and therefore no first trip to the State would be necessary.

**Comment by toomuchdesign** [comment]
Hi @RichardForrester,
in case you still needed it, I found a possible implementation of `createStructuredCachedSelector` utility that would be pretty coincise.

Here is the relevant [PR](#76).

The branch is still not ready for being merged and I'm not even sure it's actually the case.
But you can easily copy-paste it in you project.

Cheers!

**Comment by toomuchdesign** [comment]
Poll: shall we add a `createStructuredCachedSelector` utility? Ideas?

**Comment by RichardForrester** [comment]
Glass of water indeed! Nice implementation.

On balance, I'll vote to add it because even though it's technically extending the API for a convenience, it's actually simpler for folks coming from reselect to mirror the existing API instead of "creating" an exception to what is otherwise a one-to-one correlation between the two libraries.

Thanks.

**Comment by toomuchdesign** [comment]
Hi @RichardForrester,
I completed the PR for the[ introduction of `createStructuredCachedSelector`](https://github.com/toomuchdesign/re-reselect/pull/76).

I'd be glad if you could take a look to the [new relevant typings](https://github.com/toomuchdesign/re-reselect/pull/76/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R4369).

Greetings!

**Comment by RichardForrester** [comment]
I notice the addition of the ValueOf<T>. It looks good to me. I popped the function export and the typings into my project and they work the same. I notice however that I am escaping the type system all over the place with `as any` do to my own code not having been maintained with typescript consistently. But it seems right to me.

**Comment by toomuchdesign** [comment]
Shipped with [v.3.2.0](https://github.com/toomuchdesign/re-reselect/releases/tag/v3.2.0).
Thanks for your valuable feedback!
